name: spedah
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  get: ^4.6.5
  fluttertoast: ^8.1.2
  share_plus: ^6.3.0
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: "^0.12.0"
  form_validator: ^2.1.1
  pinput: ^2.2.21
  flutter_webrtc: ^0.9.25
  agora_rtc_engine: ^6.1.0
  charts_flutter: ^0.11.0
  syncfusion_flutter_charts: ^21.1.39
  persistent_bottom_nav_bar: ^5.0.2
  fl_chart: ^0.61.0
  flutter_switch: 
  custom_navigator: ^0.3.0
  custom_navigation_bar: ^0.8.2





dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.4+4
  contained_tab_bar_view: ^0.8.0
  clip_shadow: any
  intro_slider: ^4.2.0
  

  

  flutter_native_splash: 
  page_transition: ^2.0.9
  #otp_text_field: ^1.1.3
  otp_pin_field: ^1.1.2+2
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
flutter_icons:
  android: true
  ios: true
  image_path: "images/header_logo.png"


  
  
  
  
 
  
  


flutter:

  uses-material-design: true
  assets:
    - images/
    
   
  
